### PR TITLE
feat: add admin module

### PR DESCRIPTION
**Pull request by ArnabXD**

### CODE REVIEW

**Comment by ArnabXD** [comment]
Sorry for the spam lol, clicked outside by mistake twice.

**Review by roj1512 — CHANGES_REQUESTED** [review]
Related to the part of getting the entity to promote or do the action on: you should make it a helper function to not write it for all commands.

**Comment by roj1512** [comment]
Any updates?

**Comment by ArnabXD** [comment]
no working updates yet, currently stucked on ban...

**Comment by roj1512** [comment]
Why stuck?

**Comment by roj1512** [comment]
Can't you separate "the part of getting the entity to promote or to do an action on" to a helper function before thinking about other commands?

**Comment by ArnabXD** [comment]
the part of getting entity might look same but some additional steps are there, I didn't try DRY here because I was't sure if this will even worth if there is just this two cases. So I thought to - let's make them working and then refactor them properly.

> Why stuck?

Because it is not banning the user (I know stupid answer but truth lol).

**Review by roj1512 — APPROVED** [review]
@ArnabXD You can merge this if you approve my changes, too.

**Pull request merged**
