### PR TITLE
chore: setup logging

### PR DESCRIPTION
**Pull request by roj1512**

### CODE REVIEW

**Comment by roj1512** [comment]
test

**Comment by roj1512** [comment]
d

**Comment by roj1512** [comment]
test

**Comment by roj1512** [comment]
tyest

**Comment by roj1512** [comment]
t

**Comment by roj1512** [comment]
t

**Comment by roj1512** [comment]
t

**Comment by roj1512** [comment]
t

**Review by dcdunkan — APPROVED** [review]

**Pull request merged**
