### PR TITLE
fix: make the format script work on all platforms

### PR DESCRIPTION
**Pull request by roj1512**

### CODE REVIEW

**Comment by ArnabXD** [comment]
I added this because lint-staged was having issues running prettier, you can add another script like  format:lint-staged with the current command or replace `npm run format` with raw command in lint-staged

**Comment by ArnabXD** [comment]
Closed by mistake

**Comment by roj1512** [comment]
Can you try if it works when the Prettier command is this PR?

**Comment by ArnabXD** [comment]
You suggested the same code in telegram group and initially and it was failing, can't remember the reason.. I will retest.

**Comment by roj1512** [comment]
Your current command does not format the TypeScript files in `src/`, it just formats the TypeScript files in its sub-directories.

**Comment by roj1512** [comment]
You can push any other fix to the `package.json` branch, if you have.

**Comment by roj1512** [comment]
image

**Comment by roj1512** [comment]
Seems like a platform problem.

**Comment by ArnabXD** [comment]
give this a try

```js
"prettier --write \"src/**/*.ts\""
```

**Comment by roj1512** [comment]
I just found out `prettier --write src/**/*.ts` works if I run it myself (npm not running it). Trying your suggestion in the format script now.

**Comment by roj1512** [comment]
I just found out `prettier --write src/**/*.ts` works if I run it myself (npm not running it). Trying your suggestion in the format script now.

**Comment by ArnabXD** [comment]
Found this [here](https://github.com/prettier/prettier/issues/362#issuecomment-366534149)

**Review by ArnabXD — APPROVED** [review]

**Pull request merged**
