### PR TITLE
feat: disable default parse mode

### PR DESCRIPTION
**Pull request by roj1512**
- Fixes many possible problems with formatting. If something needed parsing, the parse mode must be set manually for that.

### CODE REVIEW

**Comment by ArnabXD** [comment]
How does this impact the general sendMessage/edit etc ? Do we need to pass pasrmode everytime we send/edit message ?

**Review by ArnabXD — APPROVED** [review]

**Comment by roj1512** [comment]
@ArnabXD yes, everytime.

**Comment by roj1512** [comment]
@ArnabXD if you don't like this, we can continue with https://github.com/xorgram/xor/pull/15. But this way is better in my opinion, and we can always change it in the future if we thought it's not. None of the ways are breaking anything.

**Comment by ArnabXD** [comment]
Nope, I have no issues,

**Comment by roj1512** [comment]
Wait tho.

**Pull request merged**
